<?php
session_start();
$usefsd = false;
if ((!isset($_SESSION['usfsd']) ||  !isset($_SESSION['pssfsd']) || $_SESSION['proyecto'] != 'tablillas')) {
  if (isset($_GET['fallo'])) {
    $fallo = $_GET['fallo'];
  }
  else {
    $fallo = null;
  }
}
else {
  header('location:./index.php');
}
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Entrada</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="./css/entrada.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- <script src='./js/fsd_visor.js' type="text/javascript"></script> -->
</head>
<body>
  <div class="cabecera col-md-12 w-100">
    <h1 class="col-md-6" style="margin-top:10px;">Neo-Summerian Texts Map: Log in</h1>
    <p class="col-md-6 lnk-cred">
      <a class="logo" data-toggle="modal" data-target="#acercaDe">About</a><img src="./img/logo_csic_blanco.png" title="CSIC" class="logo"/>
    </p>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="acercaDe" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Naval Trade History Map</h4>
        </div>
        <div class="modal-body">
          The Spanish National Research Council (CSIC), through the Centre for Human and Social Sciences (CCHS) put forward this map viewer, developed by the GIS Lab, to offer direct access to historical data gathered through different research projects: DynCoopNet (ESF:FP:004DynCoopNet) and ForSeaDiscovery (PITN-GA- 2013-607545).<br>Project leader: Dr. Ana Crespo Solana. Instituto de Historia, CCHS-CSIC
          <hr>
          Two different datasets are gathered in this map viewer:
          <ul>
            <li>Routes: Voyages along the main commercial routes within the Modern Ages</li>
            <li>Shipwrecks: Either known through historical sources or archaeological exploration</li>
          </ul>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <!-- Fin modal -->
  <div class="container">
      <div id="signupbox" style="margin-top:50px" class="mainbox col-md-6 col-md-offset-3">
          <div class="panel-body" style="margin-top: 100px;">
            <?php
            	if ($fallo == 'ident') {
            		echo "<strong style='color:red'>Invalid user</strong>";
            	}
            ?>
            <form method="POST" action='./datos/pas_ctr.php'>
                <div class="form-group required">
                    <label class="control-label col-md-12">User</label>
                    <div class="controls col-md-12 ">
                        <input class="form-control" name="usr" value="" style="" type="text" />
                    </div>
                </div>
                <div class="form-group required">
                    <label class="control-label col-md-12">Password</label>
                    <div class="controls col-md-12 ">
                        <input type="password" class="form-control" name="ctr" value="" style="" type="text" />
                    </div>
                </div>
                <div class="col-md-12 ">
                    <input type="submit" value="Enter" class="btn boton-entra" />
                </div>
            </form>
          </div>
      </div>
      <div class="navbar-fixed-bottom mainbox col-md-10 col-md-offset-1 beta-v">
          <p><span class="strong">Beta version web portal</span></p>
          <span class="">
             This is a resource generated by an ongoing research project (XXXX-XXXX)
          </span>
      </div>
  </div>
</body>
</html>
